### ISSUE TITLE
I am not able to compile it with Xcode 7 for iOS...

### ISSUE THREAD

**Issue by Foddy** [unixpickle/MP4Audio#2]
Hi, is it possible to use your class on an iOS app?
Overtime I try to compile it for iOS8 I get this error(s):

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_ANMovie", referenced from:
      objc-class-ref in main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by unixpickle** [comment]
Make sure you copied the ANMovie directory and all its subdirectories into your new project and set them to compile. Also make sure you import the AudioToolbox framework. Besides that, I do not know why it might not be working without giving any compilation errors.
